### ISSUE TITLE
documentation: is netem setup on the server (sending) side?

### ISSUE THREAD

**Issue by hirenp** [google/transperf#2]
Where is traffic shaping with netem being done if I have a client and a server?

**Comment by nealcardwell** [comment]
The netem traffic shaping and RTT emulation is being done on the receiver
side. (As it must be, to avoid entanglements with TSQ.)

cheers,
neal

**Comment by hirenp** [comment]
Thanks Neal, it makes sense. BTW, does the tool currently support having a separate box just doing netem/shaping?

**Comment by nealcardwell** [comment]
It does not yet support that. If someone wants to refactor the code to
support that, such a feature could be nice.

cheers,
neal
