### ISSUE TITLE
documentation: control and data flow clarification

### ISSUE THREAD

**Issue by hirenp** [google/transperf#3]
If I look at `Quick start - Multi server mode` example from readme 
$ python transperf.zip -v -x -c sample_config root@host1 root@host2 root@host3

 which node is sender vs which one is receiver our of host1, host2 and host3?
I assume sender nodes are the ones we are testing from transport protocol performance pov. 

A little more clarity in documentation could help. :-)

**Comment by lukehsiao** [comment]
The first host (host1) will be the receiver, the rest will be senders. 

This is noted in the README in that same section:

> Note that the first host provided as a command line argument is used as the receiver.
