### ISSUE TITLE
transperf in single-server mode 

### ISSUE THREAD

**Issue by DhanaSekharM** [google/transperf#4]
>python transperf.zip -v -x -c sample_config/4bbr_50M_40ms_BDP.py --virtcleanup --ssrv host1 root@rcv root@snd1 root@snd2

When run in single-server mode, does transperf handle the creation of rcv, snd1 and sn2 namespaces too or do they have to be created by the user?

**Comment by nealcardwell** [comment]
Hi,

In single-server mode, transperf automatically handles the creation of the
sender and receiver namespaces.

neal
